### PR TITLE
fixed typos for task retry 

### PR DESCRIPTION
**Pull request by pgherveou**
Sorry didnt havetime to run the tests yesterday
the test is still failing on this line not sure why

```
239. job.should.have.property('_attributes.retry');
```

### CODE REVIEW

**Comment by logicalparadox** [comment]
No worries.

The `_attributes.retry` is only applicable to the job model, not the job `object` that is inside the action callback. 

You should rebase on qualiancy/kinetik/master ... I fixed some of these (you should review though) and the tests are passing now. I thought you were done so I merged it in and Travis-CI yelled at me :P Was compelled to fix.

**Comment by pgherveou** [comment]
sorry a bout that I did add a note in the last pull-request
I ll do the rebase later this morning

**Comment by pgherveou** [comment]
mm its dirty I am not sure how to do this pull request properly but my last version pass test correctly

**Comment by logicalparadox** [comment]
Most of that last commit was doc changes made earlier. Can you do a visual inspection of where you saw issues and work off a clean copy? See if there was anything I missed and open a new PR?

**Pull request closed without merging**
